// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVK7KDmusgszY2KpwCu4OfjXRM-7OyEg0',
    appId: '1:557244960723:web:3f77c8fa91835e59036926',
    messagingSenderId: '557244960723',
    projectId: 'green-quest-a550a',
    authDomain: 'green-quest-a550a.firebaseapp.com',
    databaseURL: 'https://green-quest-a550a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'green-quest-a550a.firebasestorage.app',
    measurementId: 'G-RF80R252WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwXMosld3w8RCj8wLNkCW_Cwmq3P0iDB8',
    appId: '1:557244960723:android:916fa72d65680784036926',
    messagingSenderId: '557244960723',
    projectId: 'green-quest-a550a',
    databaseURL: 'https://green-quest-a550a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'green-quest-a550a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhRnJvq2B55o-vdvKpANSKKxxge6HjS_s',
    appId: '1:557244960723:ios:1caf37f9624f490e036926',
    messagingSenderId: '557244960723',
    projectId: 'green-quest-a550a',
    databaseURL: 'https://green-quest-a550a-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'green-quest-a550a.firebasestorage.app',
    iosBundleId: 'com.antigravity.greenquest.greenQuest',
  );
}
